# Generated by Django 4.1.1 on 2022-11-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
                ('firstName', models.CharField(max_length=90)),
                ('lastName', models.CharField(max_length=90)),
                ('documentType', models.CharField(max_length=90)),
                ('document', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=90)),
                ('itemsid', models.CharField(max_length=90)),
                ('productId', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('refId', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=200)),
                ('detailUrl', models.CharField(max_length=200)),
                ('costPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.CharField(max_length=90)),
                ('orderId', models.CharField(max_length=90)),
                ('totalValue', models.CharField(max_length=90)),
                ('paymentNames', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('statusDescription', models.CharField(max_length=90)),
                ('origin', models.CharField(max_length=90)),
                ('totalItems', models.CharField(max_length=90)),
                ('currencyCode', models.CharField(max_length=90)),
                ('hostname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingData_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressType', models.CharField(max_length=90)),
                ('receiverName', models.CharField(max_length=90)),
                ('addressId', models.CharField(max_length=90)),
                ('postalCode', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
                ('country', models.CharField(max_length=90)),
                ('street', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=90)),
                ('sellerOrderId', models.CharField(max_length=90)),
                ('origin', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('statusDescription', models.CharField(max_length=90)),
                ('value', models.CharField(max_length=90)),
                ('creationDate', models.CharField(max_length=90)),
                ('orderGroup', models.CharField(max_length=90)),
                ('clientProfileData', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='api.clientprofiledata')),
                ('items', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='api.items')),
                ('shippingData', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='api.shippingdata_address')),
            ],
        ),
    ]
